#!/bin/sh
echo "Content-type: application/json"
echo

INTERFACE=$(printf "%s" "$QUERY_STRING")

# Case: $QUERY_STRING is empty.  Treat as "dump"
if [ -z "$INTERFACE" ]; then
    ubus call network.interface dump
    exit 0
fi

# Case: Handle parameter "dump"
if [ "$INTERFACE" == "dump" ]; then
    ubus call network.interface dump
    exit 0
fi

# Case: Handle parameter "logical network interface name"
ubus call "network.interface.$INTERFACE" status
exit 0
